/*let stockProductos=[
    {id:"item1", nombre:"Cera Depilatoria Vegetal x200g", marca:"Depimiel", tipo:"depilacion", precio:"320", img:'img/Cera-Depilatoria-Vegetal-en-Perlas-Sistema-Español-x200-g-Depimiel.jpg'},
    {id:"item2", nombre:"Palo de depilación madera", marca:"LACA", tipo:"depilacion", precio:"99", img:'img/Palo-para-Depilacion.jpg'},
    {id:"item3", nombre:"Cera Depilatoria para microondas Vegetal x200g", marca:"Depimiel", tipo:"depilacion", precio:"415", img:'img/Cera-Depilatoria-para-Microondas-Vegetal-Sistema-Español-x200-g-Depimiel.jpg'},
    {id:"item4", nombre:"Repuesto cera depilatoria natural x200g", marca:"Depimiel", tipo:"depilacion", precio:"320", img:'img/Repuesto-Cera-Depilatoria-Natural-Sistema-Español-x200-g-Depimiel.jpg'},
    {id:"item5", nombre:"Cera Depilatoria para espátula x1kg", marca:"LACA", tipo:"depilacion", precio:"919", img:'img/Cera-Depilatoria-Para-Espatula-Alta-Adherencia-x1-kg-Cosmetica-Profesional.jpg'},
    {id:"item6", nombre:"Pinceles Kit de 15 pinceles para decoración de uñas", marca:"Meliné", tipo:"manicuria", precio:"1299", img:'img/Kit-de-15-Pinceles-para-decoracion-de-Uñas.jpg'},
    {id:"item7", nombre:"Removedor de esmalte semipermanente x120ml", marca:"Thuya", tipo:"manicuria", precio:"752", img:'img/Kit-de-15-Pinceles-para-decoracion-de-Uñas.jpg'},
    {id:"item8", nombre:"Lima para brillo en forma de gota", marca:"Be-High", tipo:"manicuria", precio:"190", img:'img/Kit-de-15-Pinceles-para-decoracion-de-Uñas.jpg'},
    {id:"item9", nombre:"Esmalte Top Coat Larga duración x15ml", marca:"Meliné", tipo:"manicuria", precio:"590", img:'img/Esmalte-Top-Coat-Larga-Duracion-x15-ml-Esmaltado-Tradicional.jpg'},
    {id:"item10", nombre:"Combo 5 esmaltes semipermanentes", marca: "Meliné", tipo:"manicuria", precio:"7100", img:'img/Combo-3-Esmaltes-Semipermanentes-Meline---Top-Coat---Base-Coat-Meline.jpg'},
    {id:"item11", nombre:"Paleta de sombras Eyeland Vibes x10gr", marca: "Palladio", tipo:"maquillaje", precio:"6120", img:'img/Paleta-de-Sombras-Eyeland-Vibes-x10gr-Palladio.jpg'},
    {id:"item12", nombre:"Base en polvo Wet&Dry Foundation x8gr", marca:"Palladio", tipo:"maquillaje", precio:"6520", img:'img/Base-En-Polvo-Wet-Dry-Foundation-x8gr-Palladio.jpg'},
    {id:"item13", nombre:"Mascara para pestañas 4D Boost Herbal x10ml", marca: "Palladio", tipo:"maquillaje", precio:"4872", img:'img/Mascara-para-Pestañas-4D-Boost-Herbal-x10ml-Palladio.jpg'},
    {id:"item14", nombre:"Corrector Líquido x5ml", marca: "Palladio", tipo:"maquillaje", precio:"3672", img:'img/Corrector-Liquido-x5ml-Palladio.jpg'},
    {id:"item15", nombre:"Corrector Under Eyes Disguise x10gr", marca:"Palladio", tipo:"maquillaje", precio:"3672", img:'img/Corrector-Under-Eyes-Disguise-x10gr-Palladio.jpg'},
    {id:"item16", nombre:"Aceite para masajes relajantes Sándalo x190ml", marca:"Dr. Duval", tipo:"masajes", precio:"1690", img:'img/Aceite-para-masajes-relajantes-Sandalo-x-190ml.jpg'},
    {id:"item17", nombre:"Gel Criogénico Modelador Fuerte x980gr", marca:"Exel", tipo:"masajes", precio:"4400", img:'img/Gel-Criogenico-Modelador-Fuerte-x980gr-Exel.jpg'},
    {id:"item18", nombre:"Serum Reafirmante con Nanoliposomas x250ml", marca: "Exel", tipo:"masajes", precio:"2030", img:'img/Serum-Reafirmante-con-Nano-liposomas-x250ml-Exel.jpg'},
    {id:"item19", nombre:"Gel Base para Tratamientos Cosmetológicos x240ml", marca: "Exel", tipo:"masajes", precio:"820", img:'img/Gel-Base-para-Tratamientos-Cosmetologicos-x240ml-Exel.jpg'},
    {id:"item20", nombre:"Gel Cream Hidrodesestresante x30ml", marca: "Exel", tipo:"masajes", precio:"2350", img:'img/Gel-Cream-Hidrodesestresante-x30ml-Exel.jpg'},
];*/